SELECT TOP (1000) [Entertainer]
      ,[Gender_traditional]
      ,[Birth_Year]
      ,[Year_of_Breakthrough_1_Hit_Award_Nomination]
      ,[Total_Awards_won]
      ,[Total_Nominees]
      ,[Breakthrough_Name]
      ,[Award_Won_from_Breakthrough]
      ,[Year_of_First_Oscar_Grammy_Emmy]
      ,[Year_of_Last_Major_Work_arguable]
      ,[Year_of_Death]
      ,[Oscar_Won]
      ,[Grammy_Won]
      ,[Emmy_Won]
      ,[Other_Awards]
  FROM [work].[dbo].[Entertainer_final_data]
